//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurseWaterPool
{
    using System;
    using System.Collections.Generic;
    
    public partial class pool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pool()
        {
            this.lesson = new HashSet<lesson>();
        }
    
        public int id { get; set; }
        public Nullable<int> idType { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> deth { get; set; }
        public Nullable<int> height { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lesson> lesson { get; set; }
        public virtual typePool typePool { get; set; }
    }
}
